export default {
  solo: { text: 'Solo traveller friendly', imgSrc: 'solo' },
  wildlife: { text: 'Great for wildlife', imgSrc: 'wild' },
  family: { text: 'Family owned', imgSrc: 'family' },
  vegetarian: { text: 'Vegetarian friendly', imgSrc: 'vegetarian' },
  wellbeing: { text: 'Great for wellbeing', imgSrc: 'wellbeing' },
  vegan: { text: 'Vegan', imgSrc: 'vegan' },
  makingFriends: {
    text: 'Great for making new friends',
    imgSrc: 'social',
  },
  budget: { text: 'Budget', imgSrc: '' },
  nature: { text: 'Great for nature', imgSrc: 'nature' },
  kids: { text: 'Kids friendly', imgSrc: 'kid' },
  culture: { text: 'Great for local culture', imgSrc: '' },
  midRange: { text: 'Mid range', imgSrc: '' },
  staff: { text: 'Great staff', imgSrc: 'staff' },
  luxury: { text: 'Luxury', imgSrc: 'luxury' },
  owners: { text: 'Great owners/hosts', imgSrc: '' },
};
